### ISSUE TITLE
Video of the talk

### ISSUE THREAD

**Issue by KennyMiyasato** [ticketmaster/DscDemo#1]
Does anyone happen to have the video that goes along with this? I've also been trying to find Mike Walker's contact info but haven't been able to find that either.

**Comment by mikewalker125** [comment]
Hi Kenny,

I'm not sure if a recording was posted to Youtube or not, I cannot find it. My contact info is mike.walker@ticketmaster.com, though.

**Comment by KennyMiyasato** [comment]
Thanks!
